# Use a base image
FROM openjdk:11

# Set the working directory inside the container
WORKDIR /app

# Copy the project files to the container
COPY . /app

# Build commands (if needed)



# Expose any ports required by your application
EXPOSE 8080

# Set the entry point or command to run your application
CMD ["java", "-jar", "upes.jar"]
